# Generated by Django 4.0 on 2021-12-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pizaa_name', models.CharField(max_length=400)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
