# Generated by Django 3.2.9 on 2021-12-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
