# Generated by Django 4.0 on 2021-12-11 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0004_topin'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='price',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topin',
            name='price',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
