# Generated by Django 4.0 on 2021-12-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0005_topic_price_topin_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='topin',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
