# Generated by Django 4.0 on 2021-12-12 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0007_entry_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('topin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PizzaApp.topin')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
