# Generated by Django 3.2.8 on 2021-12-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0008_entry1'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry1',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, upload_to='topics'),
        ),
        migrations.AlterField(
            model_name='topin',
            name='image',
            field=models.ImageField(blank=True, upload_to='topins'),
        ),
    ]
